# Site settings
title: Samuel Marchal > Le Blog
email: contact@smarchal.com
description: >
  Laboratoire public, ce blog est l'aggrégation de toutes
  mes expériences dans le domaine du développement web.
baseurl: ""
url: http://blog.smarchal.com
twitter_username: zessx
github_username:  zessx

# Gems
gems:
  - wdm
  - octopress-autoprefixer

# Build settings
safe: false
markdown: kramdown
permalink: /:title
sass:
  style: compressed